# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux Cluster Display Manager

on:
  push:
    branches:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pystache
        pip install gitchangelog
    - name: Generate CHANGELOG
      run: |
        git fetch
        gitchangelog
    # Commit back the CHANGELOG
    - name: Commit files
      run: |
        git config --local user.email "robot@unity3d.com"
        git config --local user.name "GitHub CHANGELOG Action"
        git commit -m "Updating Changelog" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
